
CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_time TIMESTAMP(6) WITHOUT TIME ZONE,
    description VARCHAR(500),
    modified_time TIMESTAMP(6) WITHOUT TIME ZONE,
    name VARCHAR(100),
    CONSTRAINT "groupsPK" PRIMARY KEY (id)
);

ALTER TABLE
    groups
ADD
    CONSTRAINT UC_GROUPSDESCRIPTION_COL UNIQUE (description);

ALTER TABLE
    groups
ADD
    CONSTRAINT UC_GROUPSNAME_COL UNIQUE (name);

CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT "departmentPK" PRIMARY KEY (id)
);

insert into department(name) values('satish-dpt-1');